server:
  port: 18083
spring:
  application:
    name: seckill-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:3306/seckill_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      config:
        import-check:
          enabled: true
        server-addr: nacos-server:8848
        file-extension: yaml
      discovery:
        server-addr: nacos-server:8848
  main:
    allow-bean-definition-overriding: true
logging:
  pattern:
    console: "[%d{HH:mm:ss}] - %msg%n"